---
name: prettier-plugin-xml
description: Prettier XML extension is an opinionated code formatter.
homepage: https://github.com/prettier/plugin-xml
licenses:
  - MIT
languages:
  - Xml
categories:
  - Formatter

source:
  id: pkg:npm/@prettier/plugin-xml@3.4.1

bin:
  prettierxml: npm:prettier
