---
name: Package tests

on:
  pull_request:
  workflow_dispatch:
    inputs:
      packages:
        type: string
        description: Space-separated list of package definitions to test.
        required: true

jobs:
  package-diff:
    name: Check package diffs
    runs-on: ubuntu-latest
    outputs:
      all_changed_files: ${{ steps.changed-packages.outputs.all_changed_files }}
      any_changed: ${{ steps.changed-packages.outputs.any_changed }}

    steps:
      - uses: actions/checkout@v3
      - name: Get changed package definitions
        id: changed-packages
        uses: tj-actions/changed-files@v36
        with:
          files: |
            packages/**/package.yaml

  validate:
    name: Validate package definitions
    runs-on: ubuntu-latest
    needs: package-diff
    if: ${{ github.event.inputs.packages || needs.package-diff.outputs.any_changed == 'true' }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: my-mason-registry
      - uses: actions/checkout@v4
        with:
          name: mason-org/mason-registry
          fetch-depth: 2
          path: official-mason-registry
      # - id: filelist
      #   uses: the-coding-turtle/ga-file-list@v0.2
      #   with:
      #     directory: ${{ github.action_path }}
      # - run: |
      #     echo "${{ steps.filelist.outputs.file_names }}"

      - name: current path
        run: |
          pwd
      - name: List files in the repository
        run: |
          ls

      - name: List files in the repository
        run: |
          ls $GITHUB_WORKSPACE/official-mason-registry
      - name: List files in the repository
        run: |
          ls $GITHUB_WORKSPACE/my-mason-registry
      # - shell: bash
      #   run: ./my-mason-registry/.github/workflows/validate-packages.sh
      #   env:
      #     PACKAGES: ${{ github.event.inputs.packages || needs.package-diff.outputs.all_changed_files }}
      - shell: bash
        env:
          PACKAGES: ${{ github.event.inputs.packages || needs.package-diff.outputs.all_changed_files }}
        run: |
          #!/usr/bin/env bash

          if [[ -n $RUNNER_DEBUG ]]; then
              set -x
          fi

          set -euo pipefail

          npm install -g ajv ajv-cli ajv-formats

          <<<"$PACKAGES" tr ' ' '\n' | xargs -P10 -I{} ajv validate -d {} --spec=draft2020 -c ajv-formats -s $GITHUB_WORKSPACE/official-mason-registry/schemas/package.schema.json -r '$GITHUB_WORKSPACE/official-mason-registry/schemas/{components,enums}/**/*.json'

          for pkg in $PACKAGES; do
              # Check if CRLF characters exist in the file
              if grep -q $'\x0D' "$pkg"; then
                  >&2 echo "::error file=$pkg::CRLF characters detected in the file."
                  exit 1
              fi

              # Ensure that the directory name corresponds with the package name
              pkg_name=$(sed -nE 's/name: (.+)$/\1/p' "$pkg")
              if [[ "$pkg" != "my-mason-registry/packages/${pkg_name}/package.yaml" ]]; then
                  >&2 echo "::error file=$pkg::${pkg_name} name doesn't match directory name ($pkg)."
                  exit 1
              else
                  echo "$pkg has valid package name $pkg_name"
              fi
          done
      # - uses: mason-org/actions/validate-schema@v1
      #   with:
      #     packages: ${{ github.event.inputs.packages || needs.package-diff.outputs.all_changed_files }}

  tests:
    name: Test packages
    needs: [package-diff, validate]
    if: ${{ github.event.inputs.packages || needs.package-diff.outputs.any_changed == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        # If making changes remember to update the manual workflow as well.
        target:
          - darwin_arm64
          - darwin_x64
          - linux_arm
          - linux_arm64
          - linux_arm64_gnu
          - linux_arm_gnu
          - linux_x64
          - linux_x64_gnu
          - linux_x86
          - win_arm
          - win_arm64
          - win_x64
          - win_x86

        include:
          - target: linux_x64
            runs-on: ubuntu-latest
          - target: linux_x64_gnu
            runs-on: ubuntu-latest
          - target: linux_x86
            runs-on: ubuntu-latest
          - target: linux_arm
            runs-on: ubuntu-latest
          - target: linux_arm_gnu
            runs-on: ubuntu-latest
          - target: linux_arm64
            runs-on: ubuntu-latest
          - target: linux_arm64_gnu
            runs-on: ubuntu-latest
          - target: darwin_x64
            runs-on: macos-latest
          - target: darwin_arm64
            runs-on: macos-latest
          - target: win_x64
            runs-on: windows-latest
          - target: win_x86
            runs-on: windows-latest
          - target: win_arm64
            runs-on: windows-latest
          - target: win_arm
            runs-on: windows-latest

    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3
      - uses: mason-org/actions/tests@v1
        with:
          packages: ${{ github.event.inputs.packages || needs.package-diff.outputs.all_changed_files }}
          target: ${{ matrix.target }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # This job is used for branch protection rule
  # Add this job to `Status checks that are required`
  status-check:
    name: Status check
    runs-on: ubuntu-latest
    needs: tests
    if: "failure() || cancelled()"
    steps:
      - run: exit 1
